db.url=jdbc:postgresql://172.28.128.173:5432/u2?currentSchema=java
db.username=java
db.password=java
db.pool.maxSize=10
db.pool.minIdle=2
db.pool.connectionTimeoutMs=30000
logging.level.org.springframework.jdbc.core=DEBUG