CREATE SCHEMA java AUTHORIZATION dbman;
CREATE ROLE java WITH 
NOSUPERUSER
NOCREATEDB
NOCREATEROLE
NOINHERIT
LOGIN
NOREPLICATION
NOBYPASSRLS
CONNECTION LIMIT -1;

GRANT USAGE ON SCHEMA java TO java;

CREATE TABLE java.users (
id bigserial NOT NULL,
username varchar(255) NOT NULL,
CONSTRAINT users_pk PRIMARY KEY (id),
CONSTRAINT users_unique UNIQUE (username)
);